### ISSUE TITLE
Version 1.2.0 doesn't work in Blender 2.82

### ISSUE THREAD

**Issue by GerardvanEldik** [CGCookie/blender-addon-updater#59]
Addon installs perfect. But doesn't let itself activate. After that the old one doesn't work anymore. Can't find what causes this. But not happy with this. 

Error message in old version (1.1.0):
Error: Traceback (most recent call last):
  File "C:\Users\gerar\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\chocofur_model_manager\controller.py", line 226, in execute
    process_object(obj)
  File "C:\Users\gerar\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\chocofur_model_manager\controller.py", line 221, in process_object
    scn.update()
AttributeError: 'Scene' object has no attribute 'update'

Error message in new one I cannot reproduce anymore, because after first de-installation of the addon and adding it again, the error message changed. It now says the script doesn't exist.
But this is a different message then the first one.

**Comment by GerardvanEldik** [comment]
I got the old version working again by changing row #221 to:
`bpy.context.scene.collection.objects.link(obj)`
Removed the row:
`scn.update()`

At least I can use it again.

**Comment by TheDuckCow** [comment]
Thanks for posting this, will be taking another check and see if any other updates are required. Will close when resolved and submitted to master. Thanks again!

**Comment by TheDuckCow** [comment]
Hi @GerardvanEldik I think the code/issue you posted seems to not have anything to do with the Addon Updater, but rather other code within the `chocofur_model_manager` addon. I suggest you reach out to them make updates, as the errors display do not touch the addon updater code itself. If you are not sure where to reach out, this might be a good starting place: https://chocofur.com/contact/

I would also make sure you try restarting blender as well if you just installed the update; if the addon update installed changed filenames or deleted some files or added new files, it likely will not work properly unless you fully restart blender.

Closing the issue in the meantime, but let me know if I misunderstand the situation.
